[package]
name = "rust-library"
version = "0.1.0"
authors = ["Jordan Andrews <jordandrews@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="RustLibrary"
crate-type = ["dylib"]

[dependencies]
